I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 141, in script
    with circleirisout
  File "game/script.rpy", line 141, in <module>
    with circleirisout
NameError: name 'circleirisout' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 141, in script
    with circleirisout
  File "C:\Users\Fredrik\Desktop\Ren py\renpy-6.18.3-sdk\renpy\ast.py", line 1222, in execute
    trans = renpy.python.py_eval(self.expr)
  File "C:\Users\Fredrik\Desktop\Ren py\renpy-6.18.3-sdk\renpy\python.py", line 1416, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 141, in <module>
    with circleirisout
NameError: name 'circleirisout' is not defined

Windows-post2008Server-6.2.9200
Ren'Py 6.18.3.761
SlaveSimRenPy 0.0
